// LOCAL HOST
###
GET http://localhost:8080
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/626c297790aed864ea14bd9d
###
GET http://localhost:8080/contacts/626c297790aed864ea14bd9e
###
GET http://localhost:8080/contacts/626c297790aed864ea14bd9f


/// HEROKU
###
GET https://cse-341-khermansen.herokuapp.com/
###
GET https://cse-341-khermansen.herokuapp.com/contacts
###
GET https://cse-341-khermansen.herokuapp.com/contacts/626c297790aed864ea14bd9d
###
GET https://cse-341-khermansen.herokuapp.com/contacts/626c297790aed864ea14bd9e
###
GET https://cse-341-khermansen.herokuapp.com/contacts/626c297790aed864ea14bda1
